Repository ourCat/ourCat_frontend, pull requests merged in 2021-03, with the labels that each got.

#60 feat - add redux toolkit with react-redux
  package.json
  src/actions/index.ts
  src/actions/user.ts
  src/app/store.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/slicers/index.ts
  src/slicers/user.ts
Labels: chore

#61 Refactor/card component
  src/components/molecules/Card/index.tsx
  src/pages/alarm.tsx
  src/pages/insert.tsx
  src/pages/me.tsx
  src/pages/search.tsx
Labels: refactor

#58 feat(components/arganisms) : add profile component
  src/components/organisms/Profile/index.tsx
  src/components/organisms/Profile/style.ts
  src/components/organisms/index.ts
  src/pages/index.tsx
Labels: feat

#62 Refactor/profile component
  src/common/SampleData/index.ts
  src/common/index.ts
  src/components/atoms/Label/style.ts
  src/components/organisms/Profile/index.tsx
  src/components/organisms/Profile/style.ts
  src/pages/index.tsx
Labels: refactor

#65 Feat/thumbnail component
  src/common/SampleData/index.ts
  src/components/molecules/ThumbnailList/index.tsx
  src/components/molecules/ThumbnailList/style.ts
  src/components/molecules/index.ts
  src/pages/index.tsx
Labels: feat
