Repository ourCat/ourCat_frontend, pull requests merged in 2021-05, with the labels that each got.

#71 refactor(layout/main) : main layout 수정
  public/images/backgroundImage.svg
  src/components/organisms/BottomNavigation/style.ts
  src/components/organisms/Header/style.ts
  src/layouts/Main/index.tsx
  src/layouts/Main/style.ts
Labels: refactor

#74 feat - add kakao map library(with services, clusterers) and 검색 페이지 구성
  next.config.js
  src/pages/search.tsx
  src/templates/index.ts
  src/templates/search/index.tsx
  src/templates/search/kakaoMap/index.tsx
  src/templates/search/kakaoMap/style.ts
  src/templates/search/style.ts
Labels: feat

#76 refactor - kakao Map Api with Search Page (Input에 forwardRef 추가, _doc…
  src/components/atoms/Input/index.tsx
  src/pages/_document.tsx
  src/templates/search/index.tsx
  src/templates/search/kakaoMap/index.tsx
  src/templates/search/kakaoMap/style.ts
Labels: refactor

#78 refactor : kakaoMap 컴포넌트(다른 이미지로 마커 생성, 인포윈도우 생성, 마커에 이벤트 등록)
  src/templates/search/index.tsx
  src/templates/search/kakaoMap/index.tsx
Labels: feat, refactor
