Repository ourCat/ourCat_frontend, pull requests merged in 2021-04, with the labels that each got.

#66 refactor(templates) - 전체 구조에 templates 추가
  src/pages/index.tsx
  src/templates/home/index.tsx
  src/templates/home/style.ts
  src/templates/index.ts
Labels: refactor

#67 chore : readme에 파일구조 설명
  README.md
Labels: chore

#69 feat - 홈에서 고양이 상세 페이지 연결
  src/components/molecules/Card/index.tsx
  src/pages/cat/[catId].tsx
  src/templates/catDetail/index.tsx
  src/templates/catDetail/style.ts
  src/templates/home/index.tsx
  src/templates/index.ts
Labels: feat
