Repository ourCat/ourCat_frontend, pull requests merged in 2021-08, with the labels that each got.

#87 build Error fix 작업
  src/templates/home/index.tsx
  src/templates/snsLogin/NaverLogin/index.tsx
  src/templates/withdraw/index.tsx
Labels: bug

#90 Feat/login page
  package.json
  public/images/naverLogo 1.svg
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.ts
  src/components/atoms/Icon/index.tsx
  src/components/atoms/Icon/style.ts
  src/components/organisms/Modal/LoginModal/component/Login/index.tsx
  src/components/organisms/Modal/LoginModal/component/Login/style.ts
  src/components/organisms/Modal/LoginModal/component/SignUp/index.tsx
  src/components/organisms/Modal/LoginModal/component/SignUp/style.ts
  src/components/organisms/Modal/LoginModal/component/index.ts
  src/components/organisms/Modal/LoginModal/index.tsx
  src/components/organisms/Modal/LoginModal/style.ts
  src/templates/myPage/index.tsx
Labels: feat

#91 build error fix 작업
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  docs/stories/button.stories.tsx
  package.json
  src/components/organisms/Modal/LoginModal/component/Login/index.tsx
  src/components/organisms/Modal/LoginModal/component/SignUp/index.tsx
  src/components/organisms/Modal/LoginModal/style.ts
  src/templates/myPage/index.tsx
  src/templates/withdraw/index.tsx
  yarn.lock
Labels: bug, chore
