Repository ourCat/ourCat_frontend, pull requests merged in 2021-02, with the labels that each got.

#10 Feat/add button component
  .prettierrc
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.ts
  src/components/atoms/index.ts
  src/styles/Theme.ts
  yarn.lock
Labels: feat

#11 feat(components/atoms) : Image 컴포넌트 구현
  src/components/atoms/Image/index.tsx
  src/components/atoms/Image/style.ts
Labels: feat

#14 Feat/add input component
  src/components/atoms/Input/index.tsx
  src/components/atoms/Input/style.ts
  src/components/atoms/index.ts
  src/styles/GlobalStyles.tsx
Labels: feat

#16 Chore/add ssr styled component nextjs
  .babelrc
  package.json
  src/components/atoms/Input/index.tsx
  src/components/atoms/Input/style.ts
  src/pages/_document.tsx
Labels: bug

#13 feat(components/atoms) : checkbox 컴포넌트 구현
  package.json
  src/components/atoms/index.ts
  src/components/index.ts
  src/components/molecules/CheckBox/index.tsx
  src/components/molecules/CheckBox/style.ts
  src/components/molecules/index.ts
  src/pages/index.tsx
  yarn.lock
Labels: feat

#22 refactor(components/atoms) : checkbox를 atoms으로 수정
  src/components/atoms/CheckBox/index.tsx
  src/components/atoms/CheckBox/style.ts
  src/components/atoms/index.ts
  src/components/molecules/index.ts
  src/pages/index.tsx
Labels: refactor

#23 feat(components/atom) : add TextArea component
  src/components/atoms/TextArea/index.tsx
  src/components/atoms/TextArea/style.ts
  src/components/atoms/index.ts
Labels: feat

#25 feat(components/atoms) : Range 컴포넌트 구현
  src/components/atoms/Range/index.tsx
  src/components/atoms/Range/style.ts
  src/components/atoms/index.ts
Labels: feat

#27 Refactor/atom css mixin
  src/common/Interfaces/IComponent.ts
  src/common/Interfaces/index.ts
  src/common/Mixins/index.ts
  src/common/index.ts
  src/common/type/index.ts
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.ts
  src/components/atoms/CheckBox/index.tsx
  src/components/atoms/CheckBox/style.ts
  src/components/atoms/Image/index.tsx
  src/components/atoms/Image/style.ts
  src/components/atoms/Input/index.tsx
  src/components/atoms/Input/style.ts
  src/components/atoms/Label/index.tsx
  src/components/atoms/Label/style.ts
  src/components/atoms/TextArea/index.tsx
  src/components/atoms/TextArea/style.ts
  src/components/atoms/index.ts
Labels: refactor

#30 refactor(components/atoms) : range에 mixin적용
  src/components/atoms/Range/index.tsx
  src/components/atoms/Range/style.ts
Labels: refactor

#33 feat(components/atoms) : tag 컴포넌트 구현
  src/components/atoms/Badge/index.tsx
  src/components/atoms/Badge/style.ts
  src/components/atoms/index.ts
Labels: feat

#35 Feat/add recommendation component
  public/images/img.png
  public/images/ourCatLogo.png
  src/components/atoms/Image/index.tsx
  src/components/atoms/Image/style.ts
  src/components/molecules/Recommend/index.tsx
  src/components/molecules/Recommend/style.ts
  src/components/molecules/index.ts
Labels: feat

#32 Feat/add header component
  src/components/organisms/Header/index.tsx
  src/components/organisms/Header/style.ts
  src/components/organisms/index.ts
  src/layouts/Main/index.tsx
  src/layouts/Main/style.ts
  src/layouts/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/Theme.ts
Labels: feat

#36 chore : package에 deploy script 적용
  package.json
Labels: chore

#37 chore : package에 deploy script 적용
  package.json
Labels: chore

#38 refactor(components/organisms) : add Logo image for Header
  src/components/organisms/Header/index.tsx
Labels: refactor

#43 chore : init storybook
  .storybook/main.js
  .storybook/preview.js
  docs/stories/button.stories.tsx
  package.json
  src/components/atoms/index.ts
Labels: chore

#42 Feat/add bottom navigation component
  src/components/organisms/BottomNavigation/index.tsx
  src/components/organisms/BottomNavigation/style.ts
  src/components/organisms/Header/index.tsx
  src/components/organisms/Header/style.ts
  src/components/organisms/index.ts
  src/layouts/Main/index.tsx
  src/layouts/Main/style.ts
  src/pages/alarm.tsx
  src/pages/insert.tsx
  src/pages/me.tsx
  src/pages/search.tsx
  src/styles/Theme.ts
Labels: feat

#51 refactor(components/molecules) : remove arrows
  src/components/organisms/RecommendList/index.tsx
Labels: refactor

#52 refactor(components/atoms) : edit button disable
  src/components/atoms/Button/style.ts
Labels: refactor

#57 Feat/add card component
  public/images/additional.PNG
  public/images/heart.PNG
  public/images/img.png
  public/images/star.PNG
  public/images/talk.PNG
  public/images/user.PNG
  src/common/index.ts
  src/common/paths/imgUrl.ts
  src/common/paths/index.ts
  src/common/paths/pageUrl.ts
  src/components/atoms/Image/index.tsx
  src/components/atoms/Label/index.tsx
  src/components/atoms/Label/style.ts
  src/components/molecules/Card/index.tsx
  src/components/molecules/Card/style.ts
  src/components/molecules/index.ts
  src/components/organisms/BottomNavigation/index.tsx
  src/components/organisms/BottomNavigation/style.ts
  src/components/organisms/Header/style.ts
  src/pages/index.tsx
  src/styles/Theme.ts
Labels: feat
